# Use the official Python base image
FROM python:3.9-slim

# Copy the requirements file
COPY requirements.txt .

# Set the working directory in the container
WORKDIR /

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY app.py .

# Expose the port that Streamlit runs on
#EXPOSE 8501

# Set the command to run the Streamlit app
#CMD ["streamlit", "run", "--server.port", "8501", "app.py"]
CMD ["streamlit", "run", "app.py"]