# Use the official Python base image
FROM python:3.9

# Upgrade pip to the latest version
RUN python -m pip install --upgrade pip

# Copy the requirements file
COPY requirements.txt .

# Set the working directory in the container
WORKDIR /app

RUN pip freeze > requirements.txt .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir boto3

# Copy the application code into the container
COPY app/app.py .

RUN pip install streamlit

# Expose the port that Streamlit runs on
EXPOSE 8501

# Set the command to run the Streamlit app
CMD ["streamlit", "run", "app.py", "--server.port", "8501"]
